// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8jmmarCdyGPqQYXbRW1TLdoEvrCiC4k',
    appId: '1:9328491427:web:89b4d101d6643a1b72b816',
    messagingSenderId: '9328491427',
    projectId: 'leafygreen-mobile-app-utm',
    authDomain: 'leafygreen-mobile-app-utm.firebaseapp.com',
    storageBucket: 'leafygreen-mobile-app-utm.appspot.com',
    measurementId: 'G-BCK1SNEBRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuMJ7E7tm0NPMJNg05Xi8M1poXN1XnZk',
    appId: '1:9328491427:android:e63296e23d79d8f072b816',
    messagingSenderId: '9328491427',
    projectId: 'leafygreen-mobile-app-utm',
    storageBucket: 'leafygreen-mobile-app-utm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOecW2SXGeXVoSzzhj5dgBQ6IrYCrFNNc',
    appId: '1:9328491427:ios:9c1397ac3e45db9072b816',
    messagingSenderId: '9328491427',
    projectId: 'leafygreen-mobile-app-utm',
    storageBucket: 'leafygreen-mobile-app-utm.appspot.com',
    iosBundleId: 'com.example.leafygreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOecW2SXGeXVoSzzhj5dgBQ6IrYCrFNNc',
    appId: '1:9328491427:ios:9c1397ac3e45db9072b816',
    messagingSenderId: '9328491427',
    projectId: 'leafygreen-mobile-app-utm',
    storageBucket: 'leafygreen-mobile-app-utm.appspot.com',
    iosBundleId: 'com.example.leafygreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM8jmmarCdyGPqQYXbRW1TLdoEvrCiC4k',
    appId: '1:9328491427:web:f3690f596829484872b816',
    messagingSenderId: '9328491427',
    projectId: 'leafygreen-mobile-app-utm',
    authDomain: 'leafygreen-mobile-app-utm.firebaseapp.com',
    storageBucket: 'leafygreen-mobile-app-utm.appspot.com',
    measurementId: 'G-QH8TJR7KLV',
  );
}
